events {
    worker_connections 1024;
}

http {
    include mime.types;
    sendfile on;

    server {
        listen 2006 ssl;
        listen [::]:2006 ssl;
        
        ssl_certificate /etc/nginx/ssl-certificate.crt;
        ssl_certificate_key /etc/nginx/ssl-certificate.key;
        
        error_page 497 =301 https://$host:2006$request_uri;

        try_files $uri $uri/ /index.html;

        resolver 127.0.0.1;
        autoindex off;

        server_name _;
        server_tokens off;

        root /webapp/dist;
        location /static/ {
            alias /static/;
        }

        location /source/ {
            alias /webapp/source/;
        }
        
        location /rest/ {
            proxy_pass http://bri-api-container-new:5555/;
	    proxy_read_timeout 3600s;
        }
        gzip_static on;
    }
}
